### ISSUE TITLE
create a draft for ZK 2.0.x

### ISSUE THREAD

**Issue by rallek** [rallek/EventPhotosModule#21]
The master branch should become the 2.0.x branch. For 1.5 we do have a parallel branch.

**Comment by Guite** [comment]
Isn't this done?

**Comment by rallek** [comment]
Yes it is. And it is installed once. But I want to test a bit to see if it is correct or if my changes in 1..5.x branch must be adapted. Tome to do so is rare currently.

**Comment by rallek** [comment]
tested enough, draft is available in master branch
