### ISSUE TITLE
clarify category based permissions

### ISSUE THREAD

**Issue by rallek** [rallek/EventPhotosModule#25]
If more than one category is available the categories are combined with ``or`` and not with ``and``
![grafik](https://user-images.githubusercontent.com/935250/34742898-26a1d230-f588-11e7-8b7f-f4919dd46df3.png)
``nur intern`` is excluded in permissions. As long as only this category is set the not logged in vistors are not seeing this item. As soon as another category is set e.g. ``Menschen`` it is visible.

Bug or feature? Help needed!

**Comment by Guite** [comment]
See https://github.com/rallek/EventPhotosModule/blob/master/Helper/Base/AbstractCategoryHelper.php#L352

There are two different modes:

1. `return $this->categoryPermissionApi->hasCategoryAccess($entity->getCategories()->toArray(), ACCESS_OVERVIEW);`

Allows access if the user has access to at least one selected category.


2. `return $this->categoryPermissionApi->hasCategoryAccess($entity->getCategories()->toArray(), ACCESS_OVERVIEW, true);`

Only allows access if the user has access to all selected categories.

**Comment by Guite** [comment]
Maybe I can improve customisability for that a bit tomorrow...

**Comment by Guite** [comment]
See https://github.com/Guite/MostGenerator/commit/30844893d926538a653ab9356d9051a110d4dd3f

With this you can just do:
```
protected function requireAccessForAll($entity)
{
    return true;
}
```

in https://github.com/rallek/EventPhotosModule/blob/master/Helper/CategoryHelper.php

**Comment by rallek** [comment]
@Guite: Would be great to have this as an modul option for ``Configuration/Integration``.

Nevertheless thank you for this feature. I will add it at weekend.

**Comment by rallek** [comment]
I implemented after new generating the module.
see: https://github.com/rallek/EventPhotosModule/commit/54b0002e24943cca85cd9272a371acee5afdd6b7

https://oldtimer-ig-osnabrueck.de/eventphotos/albumItem/6 
This item should not be visible if not logged in and belonging to a dedicated group but it is.

**Comment by Guite** [comment]
You added this to `CategoryHelper`, but the `AbstractCategoryHelper` is not the newest version. So it never calls the new method.

**Comment by rallek** [comment]
ups, you are right. Somehow the copying was uncomplete.
