### ISSUE TITLE
Can't create an album

### ISSUE THREAD

**Issue by PierreNau** [rallek/EventPhotosModule#33]
Hi!
Is EventPhotosModule current version compatible with Zikula 2.0.5 version?
The install is OK after I complied with the instructions
Every menu is working except "create an album" I always got the following:

**Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.**

Wht's wrog??
Many thanks for your help.
Pierre

**Comment by Guite** [comment]
Which version did you use?
It looks like the `master` branch is for Zikula 2.0.x.

**Comment by rallek** [comment]
exactly. ``master`` is generated for 2.0.x. But it is not tested. Would be breat to get som feedback for that usage.

**Comment by PierreNau** [comment]
All my apologies. I did not use the good version!! Shame on me...
The master version works perfectly with zikula 2.0.5!!
Great job Rallek and many thanks!!
