### ISSUE TITLE
hook not working?

### ISSUE THREAD

**Issue by rallek** [rallek/EventPhotosModule#8]
tried with NewsModule but Ajax failed

**Comment by Guite** [comment]
did you try deleting /web/js?

**Comment by rallek** [comment]
was my first look. Also Console is not showing anything

**Comment by rallek** [comment]
Also the translation of the strings is not working (e.g.: ``Assigned albums`` and ``attach album``)

**Comment by Guite** [comment]
> translation of the strings

Workaround: replace `{{ __('Assigned albums') }}` by `{{ __('Assigned albums', 'rkeventphotosmodule') }}` in the template.

**Comment by Guite** [comment]
See https://github.com/Guite/MostGenerator/commit/78a4ffc25c506c1d104a8b2f06a052412a224826

**Comment by Guite** [comment]
Found a few others: https://github.com/Guite/MostGenerator/commit/73f635e012919e3c91dc93c0fe0167dda3fdb173

**Comment by Guite** [comment]
Fixed in https://github.com/Guite/MostGenerator/commit/0ae739b413a7e16511569c343fbbf5b86fdef4e9 :smile:

**Comment by rallek** [comment]
done. Great job! Thanks!
